// <auto-generated />
using System;
using AirportSystems.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirportSystems.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210604102703_EnterSeedingInfoToTrips")]
    partial class EnterSeedingInfoToTrips
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AirportSystems.Models.AirportModel", b =>
                {
                    b.Property<int>("Airport_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Airport_Name")
                        .HasColumnType("text");

                    b.Property<string>("Airport_Short")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Country_City")
                        .HasColumnType("text");

                    b.Property<string>("Gate")
                        .HasColumnType("text");

                    b.HasKey("Airport_ID");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Airport_ID = 1,
                            Airport_Name = "ALAIN INTERNATIONAL AIRPORT",
                            Airport_Short = "ANN",
                            Country_City = "emirates",
                            Gate = "G11"
                        },
                        new
                        {
                            Airport_ID = 2,
                            Airport_Name = "KING HUSSAIN INTERNATIONAL AIRPORT",
                            Airport_Short = "AQJ",
                            Country_City = "JURDAN",
                            Gate = "G107"
                        },
                        new
                        {
                            Airport_ID = 3,
                            Airport_Name = "ABUDAHABI INTERNATIONAL AIRPORT",
                            Airport_Short = "AUH",
                            Country_City = "emirates",
                            Gate = "G07"
                        },
                        new
                        {
                            Airport_ID = 4,
                            Airport_Name = "BAHRAIN INTERNATIONAL AIRPORT",
                            Airport_Short = "BAH",
                            Country_City = "bahrain",
                            Gate = "G34"
                        },
                        new
                        {
                            Airport_ID = 5,
                            Airport_Name = "KING FAHD INTERNATIONAL AIRPORT",
                            Airport_Short = "DMM",
                            Country_City = "dammam",
                            Gate = "G2"
                        });
                });

            modelBuilder.Entity("AirportSystems.Models.PlaneModel", b =>
                {
                    b.Property<int>("Plane_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Airport_ID")
                        .HasColumnType("int");

                    b.Property<int?>("AirportsAirport_ID")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Plane_Name")
                        .HasColumnType("text");

                    b.Property<string>("Plane_Type")
                        .HasColumnType("text");

                    b.HasKey("Plane_ID");

                    b.HasIndex("AirportsAirport_ID");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Plane_ID = 11,
                            Airport_ID = 1,
                            Capacity = 500,
                            Plane_Name = "Airbus A300 / A310",
                            Plane_Type = "Airbus"
                        },
                        new
                        {
                            Plane_ID = 14,
                            Airport_ID = 4,
                            Capacity = 350,
                            Plane_Name = "Airbus 350",
                            Plane_Type = "Airbus"
                        },
                        new
                        {
                            Plane_ID = 15,
                            Airport_ID = 5,
                            Capacity = 250,
                            Plane_Name = "Airbus 380",
                            Plane_Type = "Airbus"
                        },
                        new
                        {
                            Plane_ID = 13,
                            Airport_ID = 3,
                            Capacity = 340,
                            Plane_Name = "Airbus 340",
                            Plane_Type = "Airbus"
                        },
                        new
                        {
                            Plane_ID = 12,
                            Airport_ID = 2,
                            Capacity = 200,
                            Plane_Name = "Airbus 330",
                            Plane_Type = "Airbus"
                        });
                });

            modelBuilder.Entity("AirportSystems.Models.TripModel", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cabin_Class")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Road_Type")
                        .HasColumnType("text");

                    b.Property<int>("Take_Off_Time")
                        .HasColumnType("int");

                    b.Property<string>("Trip_Type")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("TripID");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripID = 61132,
                            Cabin_Class = "guest",
                            Destination = "dammam",
                            Duration = 3,
                            Price = 457,
                            Road_Type = "one-way",
                            Take_Off_Time = 22,
                            Trip_Type = "Internal",
                            Weight = 30
                        },
                        new
                        {
                            TripID = 61234,
                            Cabin_Class = "first",
                            Destination = "LA-USA",
                            Duration = 10,
                            Price = 7939,
                            Road_Type = "one-way",
                            Take_Off_Time = 23,
                            Trip_Type = "international",
                            Weight = 50
                        },
                        new
                        {
                            TripID = 61345,
                            Cabin_Class = "guest",
                            Destination = "Turkey",
                            Duration = 13,
                            Price = 4211,
                            Road_Type = "round-trip",
                            Take_Off_Time = 0,
                            Trip_Type = "international",
                            Weight = 40
                        },
                        new
                        {
                            TripID = 61456,
                            Cabin_Class = "guest",
                            Destination = "NewYork-USA",
                            Duration = 14,
                            Price = 5689,
                            Road_Type = "round-trip",
                            Take_Off_Time = 19,
                            Trip_Type = "international",
                            Weight = 40
                        },
                        new
                        {
                            TripID = 61567,
                            Cabin_Class = "guest",
                            Destination = "Bali",
                            Duration = 11,
                            Price = 2945,
                            Road_Type = "one-way",
                            Take_Off_Time = 2,
                            Trip_Type = "international",
                            Weight = 40
                        });
                });

            modelBuilder.Entity("AirportSystems.Models.PlaneModel", b =>
                {
                    b.HasOne("AirportSystems.Models.AirportModel", "Airports")
                        .WithMany("Planes")
                        .HasForeignKey("AirportsAirport_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
