// <auto-generated />
using System;
using BooksStoreMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksStoreMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210605215105_Book")]
    partial class Book
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BooksStoreMVC.Models.BookModel", b =>
                {
                    b.Property<int>("ISBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("PubId")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherPubId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ISBN");

                    b.HasIndex("PublisherPubId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISBN = 1234,
                            Price = 15.6,
                            PubId = 0,
                            Title = "C# book"
                        },
                        new
                        {
                            ISBN = 1233,
                            Price = 20.899999999999999,
                            PubId = 0,
                            Title = "Java book"
                        },
                        new
                        {
                            ISBN = 1235,
                            Price = 15.6,
                            PubId = 0,
                            Title = "Design Pattren book"
                        },
                        new
                        {
                            ISBN = 1236,
                            Price = 55.0,
                            PubId = 0,
                            Title = "MVC book"
                        });
                });

            modelBuilder.Entity("BooksStoreMVC.Models.PublisherModel", b =>
                {
                    b.Property<int>("PubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PubName")
                        .HasColumnType("text");

                    b.Property<string>("PubPhone")
                        .HasColumnType("text");

                    b.HasKey("PubId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("BooksStoreMVC.Models.BookModel", b =>
                {
                    b.HasOne("BooksStoreMVC.Models.PublisherModel", "Publisher")
                        .WithMany("Book")
                        .HasForeignKey("PublisherPubId");
                });
#pragma warning restore 612, 618
        }
    }
}
