// <auto-generated />
using System;
using BooksStoreMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksStoreMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210605224025_Authers")]
    partial class Authers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BooksStoreMVC.Models.AutherModel", b =>
                {
                    b.Property<int>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthName")
                        .HasColumnType("text");

                    b.Property<string>("AuthPhone")
                        .HasColumnType("text");

                    b.HasKey("AuthId");

                    b.ToTable("Authers");

                    b.HasData(
                        new
                        {
                            AuthId = 1,
                            AuthName = "Rana Majed",
                            AuthPhone = "0555555555"
                        },
                        new
                        {
                            AuthId = 2,
                            AuthName = "Lama Majed",
                            AuthPhone = "0555555556"
                        },
                        new
                        {
                            AuthId = 3,
                            AuthName = "Saud Majed",
                            AuthPhone = "0555555557"
                        },
                        new
                        {
                            AuthId = 4,
                            AuthName = "Reema Majed",
                            AuthPhone = "0555555558"
                        },
                        new
                        {
                            AuthId = 5,
                            AuthName = "Nawal Nasser",
                            AuthPhone = "0555555559"
                        },
                        new
                        {
                            AuthId = 6,
                            AuthName = "Fatimah Saad",
                            AuthPhone = "0555555599"
                        },
                        new
                        {
                            AuthId = 7,
                            AuthName = "Aishah Majed",
                            AuthPhone = "0555555599"
                        },
                        new
                        {
                            AuthId = 8,
                            AuthName = "Razan Saud",
                            AuthPhone = "0555555599"
                        });
                });

            modelBuilder.Entity("BooksStoreMVC.Models.BookModel", b =>
                {
                    b.Property<int>("ISBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("PubId")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherPubId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ISBN");

                    b.HasIndex("PublisherPubId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BooksStoreMVC.Models.ContributorModel", b =>
                {
                    b.Property<int>("ConID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConName")
                        .HasColumnType("text");

                    b.Property<string>("ConPhone")
                        .HasColumnType("text");

                    b.HasKey("ConID");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("BooksStoreMVC.Models.PublisherModel", b =>
                {
                    b.Property<int>("PubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PubName")
                        .HasColumnType("text");

                    b.Property<string>("PubPhone")
                        .HasColumnType("text");

                    b.HasKey("PubId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("BooksStoreMVC.Models.BookModel", b =>
                {
                    b.HasOne("BooksStoreMVC.Models.PublisherModel", "Publisher")
                        .WithMany("Book")
                        .HasForeignKey("PublisherPubId");
                });
#pragma warning restore 612, 618
        }
    }
}
