// <auto-generated />
using BooksStoreMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksStoreMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210605185434_Publishers")]
    partial class Publishers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BooksStoreMVC.Models.PublisherModel", b =>
                {
                    b.Property<int>("PubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PubName")
                        .HasColumnType("text");

                    b.Property<string>("PubPhone")
                        .HasColumnType("text");

                    b.HasKey("PubId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PubId = 1,
                            PubName = "Nada Majed",
                            PubPhone = "0555555555"
                        },
                        new
                        {
                            PubId = 2,
                            PubName = "Arwa Majed",
                            PubPhone = "0555555556"
                        },
                        new
                        {
                            PubId = 3,
                            PubName = "Raghad Majed",
                            PubPhone = "0555555557"
                        },
                        new
                        {
                            PubId = 4,
                            PubName = "Lana Majed",
                            PubPhone = "0555555558"
                        },
                        new
                        {
                            PubId = 5,
                            PubName = "Nadiyah Nasser",
                            PubPhone = "0555555559"
                        },
                        new
                        {
                            PubId = 6,
                            PubName = "Majed Saad",
                            PubPhone = "0555555599"
                        },
                        new
                        {
                            PubId = 7,
                            PubName = "Saad Majed",
                            PubPhone = "0555555599"
                        },
                        new
                        {
                            PubId = 8,
                            PubName = "Mohammed Abdullah",
                            PubPhone = "0555555599"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
