// <auto-generated />
using ArtGallery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtGallery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210605084701_CreatePaintingsTable")]
    partial class CreatePaintingsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArtGallery.Models.ArtistModel", b =>
                {
                    b.Property<int>("ArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArtBio")
                        .HasColumnType("text");

                    b.Property<string>("ArtImg")
                        .HasColumnType("text");

                    b.Property<string>("ArtName")
                        .HasColumnType("text");

                    b.HasKey("ArtId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("ArtGallery.Models.PaintingModel", b =>
                {
                    b.Property<int>("PntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PntImg")
                        .HasColumnType("text");

                    b.Property<string>("PntName")
                        .HasColumnType("text");

                    b.Property<string>("PntOverview")
                        .HasColumnType("text");

                    b.Property<double>("PntPrice")
                        .HasColumnType("double");

                    b.HasKey("PntId");

                    b.ToTable("Paintings");
                });
#pragma warning restore 612, 618
        }
    }
}
