// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_management.Data;

namespace project_management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("project_management.Models.Departement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departements");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("project_management.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("DepId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DepId = 2L,
                            Email = "Mohammed_0001@company.com",
                            FirstName = "Mohammed",
                            LastName = "Al-Harbi"
                        },
                        new
                        {
                            Id = 2L,
                            DepId = 2L,
                            Email = "Abdulrahman_0021@company.com",
                            FirstName = "Abdulrahman",
                            LastName = "Bin Manea"
                        },
                        new
                        {
                            Id = 3L,
                            DepId = 2L,
                            Email = "Sara_0165@company.com",
                            FirstName = "Sara",
                            LastName = "Al-Qahtani"
                        },
                        new
                        {
                            Id = 4L,
                            DepId = 1L,
                            Email = "Mohammed_0123@company.com",
                            FirstName = "Mohammed",
                            LastName = "Al-Solami"
                        },
                        new
                        {
                            Id = 5L,
                            DepId = 3L,
                            Email = "Sultan_1000@company.com",
                            FirstName = "Sultan",
                            LastName = "Al-Ghamdi"
                        },
                        new
                        {
                            Id = 6L,
                            DepId = 5L,
                            Email = "Salim_0701@company.com",
                            FirstName = "Salim",
                            LastName = "Al-Harthi"
                        });
                });

            modelBuilder.Entity("project_management.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("DepId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProjectMgrId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DepId");

                    b.HasIndex("ProjectMgrId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DepId = 2L,
                            Description = "it's a secret",
                            Name = "Secret Project",
                            ProjectMgrId = 2L
                        });
                });

            modelBuilder.Entity("project_management.Models.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("EmpId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Design the system architecture",
                            EmpId = 3L,
                            ProjectId = 1L
                        });
                });

            modelBuilder.Entity("project_management.Models.Employee", b =>
                {
                    b.HasOne("project_management.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");
                });

            modelBuilder.Entity("project_management.Models.Project", b =>
                {
                    b.HasOne("project_management.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_management.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("ProjectMgrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("project_management.Models.Task", b =>
                {
                    b.HasOne("project_management.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_management.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
