// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApi.Data;

namespace MovieApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210605163926_SeedReviewsTable")]
    partial class SeedReviewsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MovieApi.Models.GenreModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            id = 28,
                            name = "Action"
                        },
                        new
                        {
                            id = 12,
                            name = "Adventure"
                        },
                        new
                        {
                            id = 16,
                            name = "Animation"
                        },
                        new
                        {
                            id = 35,
                            name = "Comedy"
                        },
                        new
                        {
                            id = 80,
                            name = "Crime"
                        },
                        new
                        {
                            id = 99,
                            name = "Documentary"
                        },
                        new
                        {
                            id = 18,
                            name = "Drama"
                        },
                        new
                        {
                            id = 10751,
                            name = "Family"
                        },
                        new
                        {
                            id = 14,
                            name = "Fantasy"
                        },
                        new
                        {
                            id = 36,
                            name = "History"
                        },
                        new
                        {
                            id = 27,
                            name = "Horror"
                        },
                        new
                        {
                            id = 10402,
                            name = "Music"
                        },
                        new
                        {
                            id = 9648,
                            name = "Mystery"
                        },
                        new
                        {
                            id = 10749,
                            name = "Romance"
                        },
                        new
                        {
                            id = 878,
                            name = "Science Fiction"
                        },
                        new
                        {
                            id = 10770,
                            name = "TV Movie"
                        },
                        new
                        {
                            id = 53,
                            name = "Thriller"
                        },
                        new
                        {
                            id = 10752,
                            name = "War"
                        },
                        new
                        {
                            id = 37,
                            name = "Western"
                        });
                });

            modelBuilder.Entity("MovieApi.Models.GenreMovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("GenreMovie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 35,
                            MovieId = 337404
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 80,
                            MovieId = 337404
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 27,
                            MovieId = 632357
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 28,
                            MovieId = 637649
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 80,
                            MovieId = 637649
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 28,
                            MovieId = 503736
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 27,
                            MovieId = 503736
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 53,
                            MovieId = 503736
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 28,
                            MovieId = 460465
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 14,
                            MovieId = 460465
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 12,
                            MovieId = 460465
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 28,
                            MovieId = 399566
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 12,
                            MovieId = 399566
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 878,
                            MovieId = 399566
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 28,
                            MovieId = 567189
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 53,
                            MovieId = 567189
                        },
                        new
                        {
                            Id = 17,
                            GenreId = 10752,
                            MovieId = 567189
                        },
                        new
                        {
                            Id = 18,
                            GenreId = 53,
                            MovieId = 578701
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 18,
                            MovieId = 578701
                        },
                        new
                        {
                            Id = 20,
                            GenreId = 28,
                            MovieId = 578701
                        },
                        new
                        {
                            Id = 21,
                            GenreId = 9648,
                            MovieId = 578701
                        },
                        new
                        {
                            Id = 22,
                            GenreId = 80,
                            MovieId = 823855
                        },
                        new
                        {
                            Id = 23,
                            GenreId = 18,
                            MovieId = 823855
                        },
                        new
                        {
                            Id = 24,
                            GenreId = 9648,
                            MovieId = 823855
                        },
                        new
                        {
                            Id = 25,
                            GenreId = 53,
                            MovieId = 823855
                        },
                        new
                        {
                            Id = 26,
                            GenreId = 53,
                            MovieId = 808023
                        },
                        new
                        {
                            Id = 27,
                            GenreId = 28,
                            MovieId = 808023
                        },
                        new
                        {
                            Id = 28,
                            GenreId = 80,
                            MovieId = 808023
                        },
                        new
                        {
                            Id = 29,
                            GenreId = 16,
                            MovieId = 635302
                        },
                        new
                        {
                            Id = 30,
                            GenreId = 28,
                            MovieId = 635302
                        },
                        new
                        {
                            Id = 31,
                            GenreId = 12,
                            MovieId = 635302
                        },
                        new
                        {
                            Id = 32,
                            GenreId = 14,
                            MovieId = 635302
                        },
                        new
                        {
                            Id = 33,
                            GenreId = 18,
                            MovieId = 635302
                        },
                        new
                        {
                            Id = 34,
                            GenreId = 16,
                            MovieId = 527774
                        },
                        new
                        {
                            Id = 35,
                            GenreId = 12,
                            MovieId = 527774
                        },
                        new
                        {
                            Id = 36,
                            GenreId = 14,
                            MovieId = 527774
                        },
                        new
                        {
                            Id = 37,
                            GenreId = 10751,
                            MovieId = 527774
                        },
                        new
                        {
                            Id = 38,
                            GenreId = 28,
                            MovieId = 527774
                        },
                        new
                        {
                            Id = 39,
                            GenreId = 28,
                            MovieId = 615457
                        },
                        new
                        {
                            Id = 40,
                            GenreId = 53,
                            MovieId = 615457
                        },
                        new
                        {
                            Id = 41,
                            GenreId = 80,
                            MovieId = 615457
                        },
                        new
                        {
                            Id = 42,
                            GenreId = 35,
                            MovieId = 615457
                        },
                        new
                        {
                            Id = 43,
                            GenreId = 18,
                            MovieId = 520763
                        },
                        new
                        {
                            Id = 44,
                            GenreId = 878,
                            MovieId = 520763
                        },
                        new
                        {
                            Id = 45,
                            GenreId = 53,
                            MovieId = 520763
                        },
                        new
                        {
                            Id = 46,
                            GenreId = 16,
                            MovieId = 726684
                        },
                        new
                        {
                            Id = 47,
                            GenreId = 35,
                            MovieId = 726684
                        },
                        new
                        {
                            Id = 48,
                            GenreId = 10751,
                            MovieId = 726684
                        },
                        new
                        {
                            Id = 49,
                            GenreId = 12,
                            MovieId = 726684
                        },
                        new
                        {
                            Id = 50,
                            GenreId = 35,
                            MovieId = 691179
                        },
                        new
                        {
                            Id = 51,
                            GenreId = 99,
                            MovieId = 691179
                        },
                        new
                        {
                            Id = 52,
                            GenreId = 10770,
                            MovieId = 691179
                        },
                        new
                        {
                            Id = 53,
                            GenreId = 27,
                            MovieId = 259693
                        },
                        new
                        {
                            Id = 54,
                            GenreId = 9648,
                            MovieId = 259693
                        },
                        new
                        {
                            Id = 55,
                            GenreId = 53,
                            MovieId = 259693
                        },
                        new
                        {
                            Id = 56,
                            GenreId = 28,
                            MovieId = 791373
                        },
                        new
                        {
                            Id = 57,
                            GenreId = 12,
                            MovieId = 791373
                        },
                        new
                        {
                            Id = 58,
                            GenreId = 14,
                            MovieId = 791373
                        },
                        new
                        {
                            Id = 59,
                            GenreId = 878,
                            MovieId = 791373
                        },
                        new
                        {
                            Id = 60,
                            GenreId = 27,
                            MovieId = 573680
                        },
                        new
                        {
                            Id = 61,
                            GenreId = 28,
                            MovieId = 717192
                        },
                        new
                        {
                            Id = 62,
                            GenreId = 80,
                            MovieId = 717192
                        },
                        new
                        {
                            Id = 63,
                            GenreId = 18,
                            MovieId = 717192
                        });
                });

            modelBuilder.Entity("MovieApi.Models.MovieModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("backdrop_path")
                        .HasColumnType("text");

                    b.Property<string>("imdb_id")
                        .HasColumnType("text");

                    b.Property<string>("overview")
                        .HasColumnType("text");

                    b.Property<string>("poster_path")
                        .HasColumnType("text");

                    b.Property<string>("release_date")
                        .HasColumnType("text");

                    b.Property<int>("runtime")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<double>("vote_average")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            id = 337404,
                            backdrop_path = "/sgHmoqF97bjM1HUyw43FzjzXtEr.jpg",
                            imdb_id = "tt3228774",
                            overview = "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
                            poster_path = "/A0knvX7rlwTyZSKj8H5NiARb45.jpg",
                            release_date = "2021-05-26",
                            runtime = 134,
                            title = "Cruella",
                            vote_average = 8.8000000000000007
                        },
                        new
                        {
                            id = 632357,
                            backdrop_path = "/wwFBRyekDcKXJwP0mImRJjAnudL.jpg",
                            imdb_id = "tt9419056",
                            overview = "Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.",
                            poster_path = "/bShgiEQoPnWdw4LBrYT5u18JF34.jpg",
                            release_date = "2021-03-31",
                            runtime = 99,
                            title = "The Unholy",
                            vote_average = 7.0999999999999996
                        },
                        new
                        {
                            id = 637649,
                            backdrop_path = "/77tui163estZrQ78NBggqDB4n2C.jpg",
                            imdb_id = "tt11083552",
                            overview = "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
                            poster_path = "/YxopfHpsCV1oF8CZaL4M3Eodqa.jpg",
                            release_date = "2021-04-22",
                            runtime = 119,
                            title = "Wrath of Man",
                            vote_average = 7.9000000000000004
                        },
                        new
                        {
                            id = 503736,
                            backdrop_path = "/9WlJFhOSCPnaaSmsrv0B4zA8iUb.jpg",
                            imdb_id = "tt0993840",
                            overview = "Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble: venturing into the quarantine zone to pull off the greatest heist ever attempted.",
                            poster_path = "/z8CExJekGrEThbpMXAmCFvvgoJR.jpg",
                            release_date = "2021-05-14",
                            runtime = 148,
                            title = "Army of the Dead",
                            vote_average = 6.5999999999999996
                        },
                        new
                        {
                            id = 460465,
                            backdrop_path = "/mPBI506o7gITnjoSkcyPneK9s8n.jpg",
                            imdb_id = "tt0293429",
                            overview = "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
                            poster_path = "/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg",
                            release_date = "2021-04-07",
                            runtime = 110,
                            title = "Mortal Kombat",
                            vote_average = 7.5999999999999996
                        },
                        new
                        {
                            id = 399566,
                            backdrop_path = "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
                            imdb_id = "tt5034838",
                            overview = "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
                            poster_path = "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
                            release_date = "2021-03-24",
                            runtime = 113,
                            title = "Godzilla vs. Kong",
                            vote_average = 8.0999999999999996
                        },
                        new
                        {
                            id = 567189,
                            backdrop_path = "/fPGeS6jgdLovQAKunNHX8l0avCy.jpg",
                            imdb_id = "tt0499097",
                            overview = "An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.",
                            poster_path = "/rEm96ib0sPiZBADNKBHKBv5bve9.jpg",
                            release_date = "2021-04-29",
                            runtime = 109,
                            title = "Tom Clancy's Without Remorse",
                            vote_average = 7.2000000000000002
                        },
                        new
                        {
                            id = 578701,
                            backdrop_path = "/iDdpiUnCeXvBmrkBFpL6lKsZt33.jpg",
                            imdb_id = "tt3215824",
                            overview = "A young boy finds himself pursued by two assassins in the Montana wilderness with a survival expert determined to protecting him - and a forest fire threatening to consume them all.",
                            poster_path = "/xCEg6KowNISWvMh8GvPSxtdf9TO.jpg",
                            release_date = "2021-05-05",
                            runtime = 100,
                            title = "Those Who Wish Me Dead",
                            vote_average = 7.0
                        },
                        new
                        {
                            id = 823855,
                            backdrop_path = "/yyWNPhP1HR4BTLErHcZwIUsMBvA.jpg",
                            imdb_id = "tt9013182",
                            overview = "A special crimes investigator forms an unlikely bond with a serial killer to bring down a global child sex trafficking syndicate.",
                            poster_path = "/m6bUeV4mczG3z2YXXr5XDKPsQzv.jpg",
                            release_date = "2021-05-14",
                            runtime = 107,
                            title = "I Am All Girls",
                            vote_average = 6.9000000000000004
                        },
                        new
                        {
                            id = 808023,
                            backdrop_path = "/efrdAWS63s8TTWdrI2uNdIhn1dj.jpg",
                            imdb_id = "tt4136456",
                            overview = "A lonesome stranger with nerves of steel must track down and kill a rogue hitman to satisfy an outstanding debt. But the only information he's been given is a time and location where to find his quarry. No name. No description. Nothing.",
                            poster_path = "/vXHzO26mJaOt4VO7ZFiM6No5ScT.jpg",
                            release_date = "2021-04-30",
                            runtime = 105,
                            title = "The Virtuoso",
                            vote_average = 6.2000000000000002
                        },
                        new
                        {
                            id = 635302,
                            backdrop_path = "/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg",
                            imdb_id = "tt11032374",
                            overview = "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
                            poster_path = "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
                            release_date = "2020-10-16",
                            runtime = 117,
                            title = "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
                            vote_average = 8.4000000000000004
                        },
                        new
                        {
                            id = 527774,
                            backdrop_path = "/hJuDvwzS0SPlsE6MNFOpznQltDZ.jpg",
                            imdb_id = "tt5109280",
                            overview = "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
                            poster_path = "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
                            release_date = "2021-03-03",
                            runtime = 107,
                            title = "Raya and the Last Dragon",
                            vote_average = 8.1999999999999993
                        },
                        new
                        {
                            id = 615457,
                            backdrop_path = "/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg",
                            imdb_id = "tt7888964",
                            overview = "Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a \"nobody.\" When two thieves break into his home one night, Hutch's unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.",
                            poster_path = "/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
                            release_date = "2021-03-26",
                            runtime = 92,
                            title = "Nobody",
                            vote_average = 8.5
                        },
                        new
                        {
                            id = 520763,
                            backdrop_path = "/z2UtGA1WggESspi6KOXeo66lvLx.jpg",
                            imdb_id = "tt8332922",
                            overview = "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.",
                            poster_path = "/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg",
                            release_date = "2021-05-21",
                            runtime = 97,
                            title = "A Quiet Place Part II",
                            vote_average = 7.4000000000000004
                        },
                        new
                        {
                            id = 726684,
                            backdrop_path = "/rlNnwObbMu5G2FaOUlacnUIdIIA.jpg",
                            imdb_id = "tt12816634",
                            overview = "On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!",
                            poster_path = "/msI5a9TPnepx47JUb2vl88hb80R.jpg",
                            release_date = "2021-04-04",
                            runtime = 52,
                            title = "Miraculous World: Shanghai – The Legend of Ladydragon",
                            vote_average = 7.7999999999999998
                        },
                        new
                        {
                            id = 691179,
                            backdrop_path = "/hP7dN2B5ztQgSIN5Qvk63MY4EeO.jpg",
                            imdb_id = "tt11337862",
                            overview = "The cast of Friends reunites for a once-in-a-lifetime celebration of the hit series, an unforgettable evening filled with iconic memories, uncontrollable laughter, happy tears, and special guests.",
                            poster_path = "/bT3c4TSOP8vBmMoXZRDPTII6eDa.jpg",
                            release_date = "2021-05-27",
                            runtime = 104,
                            title = "Friends: The Reunion",
                            vote_average = 8.5
                        },
                        new
                        {
                            id = 259693,
                            backdrop_path = "/sWHlCeJ2RunM5eq3FYA4VuTUNqY.jpg",
                            imdb_id = "tt3065204",
                            overview = "Lorraine and Ed Warren travel to north London to help a single mother raising four children alone in a house plagued by malicious spirits.",
                            poster_path = "/zEqyD0SBt6HL7W9JQoWwtd5Do1T.jpg",
                            release_date = "2016-05-13",
                            runtime = 134,
                            title = "The Conjuring 2",
                            vote_average = 7.2000000000000002
                        },
                        new
                        {
                            id = 791373,
                            backdrop_path = "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
                            imdb_id = "tt12361974",
                            overview = "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
                            poster_path = "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
                            release_date = "2021-03-18",
                            runtime = 242,
                            title = "Zack Snyder's Justice League",
                            vote_average = 8.5
                        },
                        new
                        {
                            id = 573680,
                            backdrop_path = "/xrAaJAn3hqkInq5kE1AGJqIGXyT.jpg",
                            imdb_id = "tt7329642",
                            overview = "In the 1930s, a young reverend and his family are forced to confront their worst fears when they discover their new home holds a horrifying secret.",
                            poster_path = "/xD9mc8JCVXA8T8u4Od7qOUBuGH4.jpg",
                            release_date = "2021-04-29",
                            runtime = 97,
                            title = "The Banishing",
                            vote_average = 6.2999999999999998
                        },
                        new
                        {
                            id = 717192,
                            backdrop_path = "/fejok33Ijc6SppiEU1cfwA9Mo2.jpg",
                            imdb_id = "tt14217100",
                            overview = "Before he built a drug empire, Ferry Bouman returns to his hometown on a revenge mission that finds his loyalty tested — and a love that alters his life.",
                            poster_path = "/w6n1pu9thpCVHILejsuhKf3tNCV.jpg",
                            release_date = "2021-05-14",
                            runtime = 106,
                            title = "Ferry",
                            vote_average = 7.0
                        });
                });

            modelBuilder.Entity("MovieApi.Models.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "The Best Movie",
                            MovieId = 399566,
                            Rating = 9.2f,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Good Movie",
                            MovieId = 637649,
                            Rating = 8.2f,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Not Bad",
                            MovieId = 503736,
                            Rating = 6.5f,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "This is best movie Ever",
                            MovieId = 578701,
                            Rating = 9.8f,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Good Movie",
                            MovieId = 615457,
                            Rating = 7.3f,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Comment = "very Bad",
                            MovieId = 717192,
                            Rating = 3.2f,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Very Good Movie",
                            MovieId = 573680,
                            Rating = 8.4f,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Comment = "The best Movie Ever Must Watch",
                            MovieId = 259693,
                            Rating = 9.5f,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Not Bad",
                            MovieId = 691179,
                            Rating = 6.5f,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Good Movie",
                            MovieId = 726684,
                            Rating = 7.3f,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("MovieApi.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProfilePic = "http://farmersca.com/wp-content/uploads/2016/07/default-profile.png",
                            UserName = "Abdullah"
                        },
                        new
                        {
                            Id = 2,
                            ProfilePic = "http://farmersca.com/wp-content/uploads/2016/07/default-profile.png",
                            UserName = "Mohammed"
                        });
                });

            modelBuilder.Entity("MovieApi.Models.GenreMovieModel", b =>
                {
                    b.HasOne("MovieApi.Models.GenreModel", "Genre")
                        .WithMany("GenreMovie")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApi.Models.MovieModel", "Movie")
                        .WithMany("GenreMovie")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApi.Models.ReviewModel", b =>
                {
                    b.HasOne("MovieApi.Models.MovieModel", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApi.Models.UserModel", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
