#pragma checksum "C:\Users\WIN\Desktop\Project02_EF_ASP.NET_MVC-main\furnitureStore\Views\Categories\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "333b92c8c5c6f1f08ac5671a90a620e101f07051"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Categories_Index), @"mvc.1.0.view", @"/Views/Categories/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\WIN\Desktop\Project02_EF_ASP.NET_MVC-main\furnitureStore\Views\_ViewImports.cshtml"
using furnitureStore;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\WIN\Desktop\Project02_EF_ASP.NET_MVC-main\furnitureStore\Views\_ViewImports.cshtml"
using furnitureStore.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"333b92c8c5c6f1f08ac5671a90a620e101f07051", @"/Views/Categories/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"433b60bc2947a456930324d2c5dfefd17fe57941", @"/Views/_ViewImports.cshtml")]
    public class Views_Categories_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\n");
#nullable restore
#line 2 "C:\Users\WIN\Desktop\Project02_EF_ASP.NET_MVC-main\furnitureStore\Views\Categories\Index.cshtml"
Write(Html.Partial("_LayoutPartial"));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"

<div class=""container text-center pt-5"">


    <div class=""card border-info mb-5"" style=""width: 300px; display: inline-block; background-color: #CBCDBB; padding: 40px"">
        <div class=""card-body"">
            <h5 class=""card-title"">Sofa and Tabel</h5>
            <p class=""card-text""> </p>
            <a href=""/Furnitures/Index"" class=""btn btn-info"">Enter</a>
        </div>


    </div>

    <div class=""card border-info mb-5"" style=""width: 300px; display: inline-block; background-color: #CBCDBB; padding: 40px "">
        <div class=""card-body"">
            <h5 class=""card-title"">     Carpet    </h5>
            <p class=""card-text""></p>
            <a href=""/Furnitures/Carpet"" class=""btn btn-info"">Enter</a>
        </div>
    </div>
</div>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
