// <auto-generated />
using CatAdoption.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatAdoption.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210604185226_AddOwners")]
    partial class AddOwners
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CatAdoption.Models.AdopterModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("occupation")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("adopter");
                });

            modelBuilder.Entity("CatAdoption.Models.CatModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdopterId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("age")
                        .HasColumnType("text");

                    b.Property<string>("breed")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<bool>("vaccination")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("cat");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AdopterId = 0,
                            LocationId = 1,
                            OwnerId = 1,
                            age = "young",
                            breed = "Domestic Shorthair",
                            description = "Hi! My name is Kat and I’m an extremely friendly curious and social 1 year old. ( Shy at first of course...;)...)....I’m told I have exotic unique markings with silky coat you can’t even dream of ...;) My ideal home has very affectionate humans who don’t mind my daily exploring. I’m super flirty and love cuddling in with my foster mom in her bed and my siblings as well. If you’re looking for a cat with a dog personality then I will be your gal. ♥️",
                            gender = "female",
                            image = "https://pet-uploads.adoptapet.com/6/2/9/547432893.jpg",
                            name = "Kat",
                            vaccination = true
                        },
                        new
                        {
                            id = 2,
                            AdopterId = 0,
                            LocationId = 2,
                            OwnerId = 1,
                            age = "young",
                            breed = " Bengal",
                            description = " They are named Beauregaurd and Antoine. They are the smartest cats I have ever interacted with and and know words and love one another deeply. They are loving yet independent and will play for hours on end with either myself or another. I have an enclosed outdoor space they love to hang out in.",
                            gender = "male",
                            image = "https://pet-uploads.adoptapet.com/8/b/9/546264169.jpg",
                            name = "Antoine and Beauregaurd",
                            vaccination = true
                        },
                        new
                        {
                            id = 3,
                            AdopterId = 0,
                            LocationId = 3,
                            OwnerId = 1,
                            age = "young",
                            breed = "Domestic Shorthair",
                            description = "Meet the ever-glamorous Elizabeth Taylor.she's 10 months old, like most celebrities, she’s reclusive and prefers a quiet environment. Elizabeth is also very shy and will require someone with patience. However, she is not shy when it’s time for cat treats! Elizabeth is a strict pescatarian, enjoying the finest fish and seafood. She also enjoys living her best life playing with her favorite toy balls. This exquisite girl has the most beautiful markings with a black whip-like tail and bangs. She is a glamorous girl and is looking for her up upscale forever home.",
                            gender = "female",
                            image = "https://pet-uploads.adoptapet.com/8/8/f/442558865.jpg",
                            name = "Elizabeth Taylor",
                            vaccination = true
                        },
                        new
                        {
                            id = 4,
                            AdopterId = 0,
                            LocationId = 4,
                            OwnerId = 2,
                            age = "Adult",
                            breed = "Domestic Shorthair",
                            description = "Nyx is a 3 years black domestic short hair cat. She is a very loving cat when she gets comfortable around you. Nyx loves playing with stuffed mice, but mainly loves lounging around the house. She is always by the door when I come home and will come say goodbye when I have to leave. She will be a bit shy at first until she gets comfortable with her surroundings. She originally was rescued from a very sad situation where she was not taken care of properly. She will require a home that is quiet and low key, and a person that will be patient with her and allow her to get used to new surroundings. Nyx has so much love to give- will you give her that chance?",
                            gender = "female",
                            image = "https://pet-uploads.adoptapet.com/2/9/5/516563701.jpg",
                            name = "Nyx",
                            vaccination = true
                        },
                        new
                        {
                            id = 5,
                            AdopterId = 0,
                            LocationId = 5,
                            OwnerId = 2,
                            age = "young",
                            breed = "Domestic Shorthair",
                            description = "Hello there! I’m Pepper, nice to meet ya!I'm 10 months old I’m a wee sweet sleepy boy looking for my tender and loving FUREVER home! One of my nicknames is Dr. Pepper! I have a doctorate in adorable from Major Cuties University. Not to brag but I graduated at the top of my class! The black smudge on my nose and spotted coat are how I got my name. My smudge and my cute little overbite are my most precious features; but I have too many to count them all. I’m quite a handsome kitten! I’m really excited to live with other kitties and maybe even a doggy! My foster home is full of furbabies- cats of all ages and even a dog! I’m well adjusted, and brave around new people!",
                            gender = "male",
                            image = "https://pet-uploads.adoptapet.com/e/5/a/536736979.jpg",
                            name = "Pepper",
                            vaccination = true
                        },
                        new
                        {
                            id = 6,
                            AdopterId = 0,
                            LocationId = 6,
                            OwnerId = 2,
                            age = "Adult",
                            breed = "Domestic Shorthair",
                            description = "Gracie Mae is a 5 years sweet and confident girl--very adventurous and brave! She's bonded to her sister, Hope, and the two ladies will be 4 years old in May 2020. Gracie Mae loves to explore and play. She also loves to cuddle A LOT. She is a talkative young lady and really enjoys affection. She may be shy with new people, but once she settles in, she's a lovebug.",
                            gender = "female",
                            image = "https://pet-uploads.adoptapet.com/7/9/6/477702221.jpg",
                            name = "Mae",
                            vaccination = true
                        });
                });

            modelBuilder.Entity("CatAdoption.Models.LocationModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("location");

                    b.HasData(
                        new
                        {
                            id = 1,
                            address = "505 broadway st",
                            name = "Vetsreet",
                            phone = "303849244"
                        },
                        new
                        {
                            id = 2,
                            address = "404 broadway st",
                            name = "Pawpatrol",
                            phone = "758348939"
                        },
                        new
                        {
                            id = 3,
                            address = "303 broadway st",
                            name = "smartPet",
                            phone = " 7548484844 "
                        },
                        new
                        {
                            id = 4,
                            address = "202 broadway st",
                            name = "walmart",
                            phone = " 657474384 "
                        },
                        new
                        {
                            id = 5,
                            address = "102 broadway st",
                            name = "Pet",
                            phone = " 7548484844 "
                        },
                        new
                        {
                            id = 6,
                            address = "30 broadway st",
                            name = "kittycat",
                            phone = " 8545499504 "
                        },
                        new
                        {
                            id = 7,
                            address = "30 broadway st2",
                            name = "kittycat2",
                            phone = " 85454995042 "
                        });
                });

            modelBuilder.Entity("CatAdoption.Models.OwnerModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("reason")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("owner");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 24,
                            email = "roro@gmail.com",
                            gender = "female",
                            image = "https://images.unsplash.com/photo-1508002366005-75a695ee2d17?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80",
                            name = "Rose",
                            phone = " 85454995042 ",
                            reason = "relocating"
                        },
                        new
                        {
                            id = 2,
                            age = 54,
                            email = "jojo@gmail.com",
                            gender = "male",
                            image = "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80",
                            name = "Jack",
                            phone = " 46736437743 ",
                            reason = "relocating"
                        });
                });

            modelBuilder.Entity("CatAdoption.Models.CatModel", b =>
                {
                    b.HasOne("CatAdoption.Models.AdopterModel", "Adopter")
                        .WithMany("cats")
                        .HasForeignKey("AdopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatAdoption.Models.LocationModel", "Location")
                        .WithOne("cat")
                        .HasForeignKey("CatAdoption.Models.CatModel", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatAdoption.Models.OwnerModel", "Owner")
                        .WithMany("cats")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
