// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuwaiq_Student_Life.Data;

namespace Tuwaiq_Student_Life.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.InstructorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "",
                            Email = "Salem@Salem",
                            FirstName = "Salem",
                            LastName = "Ahamd",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Bio = "",
                            Email = "Hanaa@Hanaa",
                            FirstName = "Hanaa",
                            LastName = "Abdullah",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Bio = "",
                            Email = "Waleed@Waleed",
                            FirstName = "Waleed",
                            LastName = "Rashed",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 4,
                            Bio = "",
                            Email = "Rawan@Rawan",
                            FirstName = "Rawan",
                            LastName = "Yousef",
                            SubjectId = 3
                        });
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.InstructorStudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int?>("StudenId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudenId");

                    b.ToTable("InstructorsStudents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstructorId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            InstructorId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            InstructorId = 1,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            InstructorId = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            InstructorId = 1,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            InstructorId = 2,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 7,
                            InstructorId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 8,
                            InstructorId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 9,
                            InstructorId = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 10,
                            InstructorId = 3,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 11,
                            InstructorId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 12,
                            InstructorId = 4,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 13,
                            InstructorId = 4,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 14,
                            InstructorId = 4,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.SessionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Duration")
                        .HasColumnType("float");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Amal@Amal",
                            FirstName = "Amal",
                            LastName = "Fahad"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Leenah@Leenah",
                            FirstName = "Leenah",
                            LastName = "Ahmad"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Sarah@Sarah",
                            FirstName = "Sarah",
                            LastName = "Ali"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Reem@Reem",
                            FirstName = "Reem",
                            LastName = "Khalid"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Ali@Ali",
                            FirstName = "Ali",
                            LastName = "Saad"
                        });
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.StudentSessionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int?>("StudenId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudenId");

                    b.ToTable("StudentsSessions");
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.SubjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectName = "MVC .Net"
                        },
                        new
                        {
                            Id = 2,
                            SubjectName = "Design Patterns"
                        },
                        new
                        {
                            Id = 3,
                            SubjectName = "Unit testing"
                        });
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.InstructorModel", b =>
                {
                    b.HasOne("Tuwaiq_Student_Life.Models.SubjectModel", "Subject")
                        .WithMany("Instructors")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.InstructorStudentModel", b =>
                {
                    b.HasOne("Tuwaiq_Student_Life.Models.InstructorModel", "Instructor")
                        .WithMany("Students")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuwaiq_Student_Life.Models.StudentModel", "Studen")
                        .WithMany("Instructors")
                        .HasForeignKey("StudenId");
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.SessionModel", b =>
                {
                    b.HasOne("Tuwaiq_Student_Life.Models.InstructorModel", "Instructor")
                        .WithMany("Sessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tuwaiq_Student_Life.Models.StudentSessionModel", b =>
                {
                    b.HasOne("Tuwaiq_Student_Life.Models.SessionModel", "Instructor")
                        .WithMany("Students")
                        .HasForeignKey("InstructorId");

                    b.HasOne("Tuwaiq_Student_Life.Models.StudentModel", "Studen")
                        .WithMany("Sessions")
                        .HasForeignKey("StudenId");
                });
#pragma warning restore 612, 618
        }
    }
}
