// <auto-generated />
using HospitalDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalDatabase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210604211231_AddedDepartmentTablesData")]
    partial class AddedDepartmentTablesData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HospitalDatabase.Models.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            Location = "2nd Floor",
                            Name = "General Medicine"
                        },
                        new
                        {
                            Id = 21,
                            Location = "3rd Floor",
                            Name = "Surgery"
                        },
                        new
                        {
                            Id = 22,
                            Location = "4th Floor",
                            Name = "Psychiatry"
                        });
                });

            modelBuilder.Entity("HospitalDatabase.Models.DoctorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "General Medicine",
                            Email = "YasminG@hotmail.com",
                            FirstName = "Yasmin",
                            LastName = "AlGhamdi",
                            PhoneNumber = "055-569-9110"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Surgery ",
                            Email = "RitaF@hotmail.com",
                            FirstName = "Rita",
                            LastName = "Farr",
                            PhoneNumber = "050-569-9110"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Psychiatry",
                            Email = "TonyR@hotmail.com",
                            FirstName = "Tony",
                            LastName = "Roberts",
                            PhoneNumber = "054-932-6548"
                        },
                        new
                        {
                            Id = 4,
                            Department = "General Medicine",
                            Email = "AmeliaO@hotmail.com",
                            FirstName = "Amelia",
                            LastName = "Owen",
                            PhoneNumber = "051-436-5094"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Surgery ",
                            Email = "KyleF@hotmail.com",
                            FirstName = "Kyle",
                            LastName = "Fox",
                            PhoneNumber = "059-330-4393"
                        });
                });

            modelBuilder.Entity("HospitalDatabase.Models.MedicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("HospitalDatabase.Models.PatientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Email = "AlexiaP@hotmail.com",
                            FirstName = "Alexia",
                            LastName = "Perry",
                            PhoneNumber = "055-099-4432"
                        },
                        new
                        {
                            Id = 11,
                            Email = "PenelopeR@hotmail.com",
                            FirstName = "Penelope",
                            LastName = "Ray",
                            PhoneNumber = "054-090-5326"
                        },
                        new
                        {
                            Id = 12,
                            Email = "NoahR@hotmail.com",
                            FirstName = "Noah",
                            LastName = "Roberts",
                            PhoneNumber = "053-675-4490"
                        },
                        new
                        {
                            Id = 13,
                            Email = "LukeL@hotmail.com",
                            FirstName = "Luke",
                            LastName = "Luna",
                            PhoneNumber = "055-546-3210"
                        },
                        new
                        {
                            Id = 14,
                            Email = "TimothyR@hotmail.com",
                            FirstName = "Timothy",
                            LastName = "Riley",
                            PhoneNumber = "053-556-7432"
                        },
                        new
                        {
                            Id = 15,
                            Email = "BellaH@hotmail.com",
                            FirstName = "Bella",
                            LastName = "Holt",
                            PhoneNumber = "058-903-8953"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
