// <auto-generated />
using HospitalDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalDatabase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210604205859_AddedDoctorTablesData")]
    partial class AddedDoctorTablesData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HospitalDatabase.Models.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HospitalDatabase.Models.DoctorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "General Medicine",
                            Email = "YasminG@hotmail.com",
                            FirstName = "Yasmin",
                            LastName = "AlGhamdi",
                            PhoneNumber = "055-569-9110"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Surgery ",
                            Email = "RitaF@hotmail.com",
                            FirstName = "Rita",
                            LastName = "Farr",
                            PhoneNumber = "050-569-9110"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Psychiatry",
                            Email = "TonyR@hotmail.com",
                            FirstName = "Tony",
                            LastName = "Roberts",
                            PhoneNumber = "054-932-6548"
                        },
                        new
                        {
                            Id = 4,
                            Department = "General Medicine",
                            Email = "AmeliaO@hotmail.com",
                            FirstName = "Amelia",
                            LastName = "Owen",
                            PhoneNumber = "051-436-5094"
                        },
                        new
                        {
                            Id = 5,
                            Department = "Surgery ",
                            Email = "KyleF@hotmail.com",
                            FirstName = "Kyle",
                            LastName = "Fox",
                            PhoneNumber = "059-330-4393"
                        });
                });

            modelBuilder.Entity("HospitalDatabase.Models.MedicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("HospitalDatabase.Models.PatientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
